### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XShockinFireX** [Ad5001/BetterRaw#1]
Unhandled exception executing command 'saytip &6All Entity's Have Been Cleared!' in saytip: Undefined variable: id

UndefinedVariableException: "Undefined variable: id" (E_NOTICE) in "/BetterRaw_v1.7.phar/src/Ad5001/BetterRaw/Main" at line 347

**Comment by Ad5001** [comment]
Thx for signaling new 1.7.1 with that correct comming soon :)

**Comment by XShockinFireX** [comment]
Np!
