### ISSUE TITLE
Incompatible API version on latest build

### ISSUE THREAD

**Issue by bleonard252** [Ad5001/BetterRaw#2]
I wanted to use the latest release with the latest PocketMine version and it gives me an incompatible API version error. If it can be fixed I'm PHP inexperienced and need a fix. This is a really good plugin (in concept), though!

**Comment by Ad5001** [comment]
This version in github may be outdated so please use last version on Imagicalmine :)
https://forums.imagicalmine.net/plugins/betterraw.53/
If it don't work, please change to the last ImagicalMine (that is more advenced than pocketmine) ;)

**Comment by Ad5001** [comment]
And if it still don't work can you tell me which error is in the console ?

**Comment by bleonard252** [comment]
The upgrade to ImagicalMine helped in enabling. Now to see if it works!
It works. My new problem is my Minecraft version is 0.14.1, while ImagicalMine is 0.14.0.
Do you know any link to dev build or beta build supporting 14.1?

**Comment by Ad5001** [comment]
0.14.0 servers are compatible with 0.14.1 clients :smile: so you can connect to it :)

**Comment by bleonard252** [comment]
For some reason one of my plugins (that came with ImagicalMine) are returning this error:
[code][14:47:42] system> BlakesUnited[/192.168.1.126:19132] logged out due to Outdated server!
[/code]

**Comment by Ad5001** [comment]
Oh! This came from ImagicalMine but I don't have the bug o.O so if you didn't did i yet, download it from jenkins.imagicalmine.net  or download the files from github :)

**Comment by bleonard252** [comment]
Do you have any of the plugins from their github build? If so, which ones do you not have? I kinda need to see which one is kicking me off. :laughing:

**Comment by Ad5001** [comment]
It's not a plugin, it's imagicalmine itself that did that! just update and it will work :smile:

**Comment by bleonard252** [comment]
I just got the jenkins one...

**Comment by Ad5001** [comment]
so then just download the 'src' folder from their github, unzip it, put it in your server folder then deleted the ImagicalMine.phar and it should work :wink:

**Comment by bleonard252** [comment]
still not working :( uh oh... uhm im checking my configs ...

**Comment by bleonard252** [comment]
Deleted some iMagicalMine plugins, working now!
